### ISSUE TITLE
argument(plugin_name)) 0/1

### ISSUE THREAD

**Issue by emnkse** [MischaTheEvil/redmine_google_calendar#16]
hi;
i'm having problems with installation of google calendar plugin. i have git version 1.7.9.5 and rails version 1.9.1
a) I am trying to install with using git-rails install ... command but it returns "argument(plugin_name)) 0/1" .

b) when i try to use git clone command and restart redmine server, phusion passenger gives following errors.

uninitialized constant RAILS_DEFAULT_LOGGER (NameError)
  /usr/share/redmine/plugins/redmine_google_calendar/init.rb:20:in `<top (required)>'
  /usr/share/redmine/lib/redmine/plugin.rb:133:in`block in load'
  /usr/share/redmine/lib/redmine/plugin.rb:124:in `each'
  /usr/share/redmine/lib/redmine/plugin.rb:124:in`load'
  /usr/share/redmine/config/initializers/30-redmine.rb:19:in `<top (required)>'
  /var/lib/gems/1.9.1/gems/railties-3.2.16/lib/rails/engine.rb:593:in`block (2 levels) in class:Engine'
  /var/lib/gems/1.9.1/gems/railties-3.2.16/lib/rails/engine.rb:592:in `each'
  /var/lib/gems/1.9.1/gems/railties-3.2.16/lib/rails/engine.rb:592:in`block in class:Engine'
  /var/lib/gems/1.9.1/gems/railties-3.2.16/lib/rails/initializable.rb:30:in `instance_exec'
  /var/lib/gems/1.9.1/gems/railties-3.2.16/lib/rails/initializable.rb:30:in`run'
  /var/lib/gems/1.9.1/gems/railties-3.2.16/lib/rails/initializable.rb:55:in `block in run_initializers'
  /var/lib/gems/1.9.1/gems/railties-3.2.16/lib/rails/initializable.rb:54:in`each'
  /var/lib/gems/1.9.1/gems/railties-3.2.16/lib/rails/initializable.rb:54:in `run_initializers'
  /var/lib/gems/1.9.1/gems/railties-3.2.16/lib/rails/application.rb:136:in`initialize!'
  /var/lib/gems/1.9.1/gems/railties-3.2.16/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /usr/share/redmine/config/environment.rb:14:in`<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in`block in <main>'
  /var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
  /var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in`initialize'
  config.ru:1:in `new'
  config.ru:1:in`<main>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.37/helper-scripts/rack-preloader.rb:112:in `eval'
  /var/lib/gems/1.9.1/gems/passenger-4.0.37/helper-scripts/rack-preloader.rb:112:in`preload_app'
  /var/lib/gems/1.9.1/gems/passenger-4.0.37/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.37/helper-scripts/rack-preloader.rb:29:in`module:PhusionPassenger'
  /var/lib/gems/1.9.1/gems/passenger-4.0.37/helper-scripts/rack-preloader.rb:28:in `<main>'

**Comment by alopezbnt** [comment]
I have the same problem
